---

name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build executable
        run: go build -v -x
        env:
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: dump-${{ matrix.goarch }}
          path: dump
